### ISSUE TITLE
Be more opinionated on config file naming

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_bootstrap#171]
There are a lot of opinions on how to handle configuration in Elixir and Nerves. This issue isn't meant to change the general strategy, but to the make organization more consistent between projects and to provide hints to new Nerves users.

## Background

Here's the current setup:

```
config.exs <-- configuration for every mix target and environment
target.exs <-- configuration for all non-host targets
```

Projects that work on multiple devices uncomment a line at the bottom of `target.exs` and have a setup that looks like:

```
config.exs
target.exs
rpi0.exs
bbb.exs
```

Non-poncho projects frequently have unit tests. It's probably easier to run `mix test` with the `--no-start` option to avoid starting the application and instead manually starting GenServers, etc. in the unit tests so that it's easier to inject config. (aka `aliases: [test: "test --no-start"]` in the `mix.exs` and `start_supervised/2` in the tests.) However, if application environment still needs to be set for tests, then the normal thing to do is to add a `test.exs` and an `if` in `config.exs` to conditionally include it.

Finally, for those projects that have differences between `MIX_ENV=dev` and `MIX_ENV=prod`, the pattern that I've seen most is to add `dev.exs` and `prod.exs` just like was done for the unit tests.

I have not seen projects with config file names that combine the Mix environment and the Mix target. I feel like at that level, I've only seen conditionals.

I have also never seen someone have `host.exs`. I suspect that the contents would be the same as `test.exs`. It seems like if you like to run `iex -S mix`, then you may want `host.exs`, though.

## Proposal

Since Nerves configuration is probably more dependent on the Mix target for most projects, change the generator to make the following files:

```
config.exs
target.exs
host.exs
```

In the `config.exs`, change the `if` at the bottom to always load `host.exs` when the target is the host. In the `host.exs` add a comment about what to put in this file.

Everything else stays the same. I.e., if you want specialization based on hardware, you still uncomment the line at the end of `target.exs` to load the specific target. 

Finally, we encourage people to not create `dev.exs`, `prod.exs`, and `test.exs` files, but rather to add conditionals or `Mix.env()` checks inside the other files. The rationale is that the differences between those are small, so it will be easier to read if it's not broken out.

Thoughts?

**Comment by batate** [comment]
This newbie likes this approach. It makes it easy to put the right thing in the right place, and costs the user little if they don't use all of the files.

**Comment by fhunleth** [comment]
FYI - It was easy to turn this into a PR. I'll update #172 as people comment.
