### ISSUE TITLE
Remove legacy `:""` workaround

### ISSUE THREAD

**Issue by mnishiguchi** [nerves-project/nerves_bootstrap#217]
https://github.com/mnishiguchi/nerves_bootstrap/blob/fe0c212b9dbdd0e074030e2829b96bf8c4d7f58a/templates/new/config/config.exs#L29

I believe this is fixed in Elixir language https://github.com/elixir-lang/elixir/pull/10537. We should remove it at some stage. Maybe this is intentional for backward compatibility? 🤔

**Comment by fhunleth** [comment]
Yes, it was intentionally kept for backward compatibility. However, we're going to be moving the minimum supported Elixir version to 1.11, so the workaround can be removed now. I'm pushing the updates now. Thank you!
