### ISSUE TITLE
Do not conditionally define application, instead use a config and choose the children in the start/2 callback

### ISSUE THREAD

**Issue by josevalim** [nerves-project/nerves_bootstrap#42]

**Comment by ConnorRigby** [comment]
You are referring to this correct?
https://github.com/nerves-project/nerves_bootstrap/blob/master/templates/new/mix.exs#L34-L49

**Comment by mobileoverlord** [comment]
Yep that’s the one.

**Comment by ConnorRigby** [comment]
This has bugged me for a while, but never enough to actually deal with it. I'll take a look at it later
