### ISSUE TITLE
New projects generated with --init-gadget crash in Host mode

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-project/nerves_bootstrap#58]
When specifying `--init-gadget`, the generated mix project will contain `nerves_init_gadget` as part of the `target` only deps. The issue is that the generated `config.exs` configures the `logger` backend to use `RingLogger`. The application crashes because the application `ring_logger` is only available in the target environment.

Here are a few options we have:
1. if `--init-gadget`, we add `nerves_init_gadget` to the target only deps and also add `ring_logger` to the all deps.
2. We _always_ include RingLogger by default and put it in all deps.
3. We do not configure logger backends when `--init-gadget` is passed

My opinion is that I can not live life without ring logger, so I would move for option 2.

@fhunleth @GregMefford @ConnorRigby 
What are your thoughts.

**Comment by fhunleth** [comment]
I like `ring_logger`, so :+1:.

**Comment by fhunleth** [comment]
My only hesitation on this is that it's not obvious to new people where logs get printed. The sample `iex.exs` might be able to print a hint about calling `RingLogger.tail` to see what's happening.

**Comment by mobileoverlord** [comment]
`iex.exs` is a good start, but it is only evaluated on the console session. It would be really nice to figure out if its possible to invoke it for remote shells and ssh connections.

**Comment by ConnorRigby** [comment]
Little late to this one, but i also like `ring_logger` :+1:
