### ISSUE TITLE
--init-gadget feature expansion

### ISSUE THREAD

**Issue by johnwahba** [nerves-project/nerves_bootstrap#68]
It'd be useful if init-gadget was a string flag instead that would parameterize `usb` or `eth`

**Comment by GregMefford** [comment]
I believe we can close this now, given that `nerves_pack` and `vintage_net` make it easier to support multiple interfaces more seamlessly.

Sound good, @fhunleth @mobileoverlord?

**Comment by fhunleth** [comment]
Agree
