### ISSUE TITLE
Only include `toolshed` in target deps

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_bootstrap#87]
https://github.com/nerves-project/nerves_bootstrap/blob/master/templates/new/mix.exs#L48
This should only be in the target deps as it prevents running `iex -S mix` as `host`

**Comment by mobileoverlord** [comment]
This should work though. Toolshed doesn't do anything Nerves specific unless `nerves_runtime` is present.

**Comment by ConnorRigby** [comment]
Ah i see what happened. The user i was helping had `nerves_firmware_ssh` in his host deps, which pulled in `nerves_runtime`: https://github.com/nerves-project/nerves_firmware_ssh/blob/master/mix.exs#L33
